# Generated by Django 5.1.7 on 2025-03-12 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('auteur', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
    ]
